name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libgl1-mesa-dev \     # OpenGL
            libglfw3-dev \        # GLFW
            libglm-dev

      - name: Configure and Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build --config Release --parallel $(nproc)
