name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install CMake
        run: brew install cmake
      - name: Install Dependencies
        run: |
          brew install glfw pkg-config
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Xcode" -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_EXAMPLES=OFF
          xcodebuild -configuration Release
